# Generated by Django 5.2.8 on 2025-11-18 00:21

import django.db.models.deletion
import salas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sala')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('habilitada', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, validators=[salas.models.validar_rut], verbose_name='RUT')),
                ('nombre_reservante', models.CharField(max_length=200, verbose_name='Nombre del Reservante')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_hora_fin', models.DateTimeField(verbose_name='Fecha y Hora de Fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación de Reserva')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
    ]
