# Generated by Django 5.2.8 on 2025-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='activa', max_length=20, verbose_name='Estado'),
        ),
    ]
